const styles = {
  bgImageStyleHome: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    zIndex: -1,
    backgroundImage: `url(${process.env.PUBLIC_URL}/image/Construction-photo%201.png)`,
    backgroundRepeat: "no-repeat",
    height: "800px",
    justifyContent: "center",
    alignItems: "center",
  },
  navlink: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    position: "absolute", 
    top: "50px", 
    left: 0,
    width: "100%",
    height: "80px",
    padding: "10px 20px",
    zIndex: "1000",
    transition: "top 0.3s ease", 
  },
  links: {
    display: "flex",
    flexDirection: "row",
    gap: "50px",
    marginTop: "34px",
  },
  isActive: {
    textDecoration: "underline yellow",
  },
  leftStyles: {
    borderRadius: "50%",
    color: "white",
    backgroundColor: "grey",
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  homeDiv: {
    position: "absolute", 
    top: 0, 
    color: "white",
    marginRight: "820px",
    marginTop: "240px",
  },
  tag: {
    width: "620px",
    fontSize: "34px",
  },
  prg: {
    height: "104px",
    width: "622px",
  },
  homeBtn: {
    width: "140px",
    height: "36px",
    marginTop: "60px",
    backgroundColor: "yellow",
    padding: "8px 8px 8px 8px",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    backgroundColor: "#1E1D1D",
    zIndex: -99,
    position: "absolute",
  },
  ustunDiv: {
    display: "flex",
    flexDirection: "column",
    marginTop: "10px",
    justifyContent: "center",
    alignItems: "center",
  },
  ustunSpan: {
    fontSize: "60px",
    color: "#358A9F",
    fontFamily: "arial,sans-serif",
    fontWeight: "bold",
    marginTop: "40px",
  },
  ustunDivs: {
    display: "flex",
    flexDirection: "row",
    gap: "14px",
  },

  oxuBtn: {
    width: "200px",
    height: "36px",
    backgroundColor: "#272727",
    color: "yellow",
    padding: "8px 8px 8px 8px",
  },
  layiDiv: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "80px",
  },
  layiImgDiv: {
    display: "flex",
    flexDirection: "row",
    marginTop: "40px",
    height:"460px"
  },

 
  resmSpan: {
    position: "absolute",
    color: "white",
    padding: "26px",
    bottom: "0",
    left: "0",
    right: "0",
    display: "flex",
    flexDirection: "row",
  },
  xeberDivs: {
    display: "flex",
    gap: "16px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  cardDiv: {
    maxWidth: "400px",
    height: "560px",
    backgroundColor: "#1E1D1D",
    color: "white",
    marginTop: "40px",
  },
  cardaAct: {
    display: "flex",
    justifyContent: "space-between",
    paddingLeft: "0",
    marginTop: "10px",
  },
  cardCon: {
    paddingLeft: "0",
  },
  newsDiv: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    margin: "80px",
  },
  footSpan: {
    fontWeight: "bold",
    fontSize: "66px",
    fontFamily: "arial,sans-serif",
    color: "white",
  },
  footerS: {
    display: "flex",
    marginLeft: "270px",
    flexDirection: "column",
    marginTop: "100px",
  },
  footDiv: { display: "flex", marginLeft: "400px" },
  footLinks: {
    display: "flex",
    flexDirection: "row",
    width: "600px",
    flexWrap: "wrap",
  },
  footLinkSpan: { fontSize: "21px", marginRight: "80px", color: "white" },
  inLink: {
    color: "white",
    textDecoration: "none",
    alignItems: "center",
    display: "flex",
  },
  aboneDiv: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  inpFoot: { padding: "6px", width: "224px", height: "32px" },
  emailDiv: {
    backgroundColor: "yellow",
    width: "42px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  xSpan: { fontSize: "22px", fontWeight: "bold", color: "white" },
  copyDiv: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "white",
    margin: "40px 0 40px 0",
  },

  prgAb: {
    height: "204px",
    width: "490px",
  },
  abCon: {
    display: "flex",
    flexDirection: "column",
    marginTop: "80px",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  abDiv: {
    display: "flex",
    flexDirection: "row",
    marginTop: "60px",
    gap: "100px",
  },
  pTag: { width: "580px", color: "white", fontSize: "24px" },
  hr: { border: "1px solid #FFFC00", width: "240px" },
  abPDivs: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
  },
  prgTeams: {
    height: "204px",
    width: "560px",
  },

  projectsDiv: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  prSpan: {
    color: "white",
    fontSize: "20px",
    fontFamily: "arial,sans-serif",
  },
  ul: {
    color: "white",
    fontFamily: "arial,sans-serif",
    width: "950px",
    fontSize: "24px",
    height: "160px",
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "column",
  },
  contactDiv:{
    display: "flex",
    backgroundColor: "#2D2D2D",
    width: "1440px",
    height: "845px", 
    margin: "auto", 
    marginTop:"80px",
},
if:{
  width: "720px", 
  height: "845px",
  border: "0", 
  overflow: "hidden", 
  margin: "0 auto", 
  display: "block", 
},
ifDiv:{
  width:"720px",
  height:"845px",
},
avDivs:{width:"720px",display:"flex",flexDirection:"column",alignItems:"center"},
pCon:{fontSize:"45px",fontWeight:"bold",color:"white"},
avDiv:{display:"flex",width:"513px",height:"94px",gap:"12px",alignItems:"center"},
textCon:{width:"370px",fontSize:"16px",height:"88px",color:"white",border:"1px solid #5A5A5A",borderRadius:"12px",},
formS:{display:"flex",gap:"30px",flexDirection:"column"},
inpDiv:{display:"flex",flexDirection:"column",gap:"8px"},
labelS:{fontSize:"16px",color:"#8D8D8D"},
inpS:{width:"515px",height:'58px',padding:"8px",backgroundColor:"#343333",border:"1px solid #8D8D8D",borderRadius:"8px"},
conBtn:{border:"1px solid #8D8D8D",width:"250px",height:"50px",color:"yellow",borderRadius:"8px"},
};

export default styles;
